name: meals_riverpod_app
description: "Meals Riverpod App"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  #fonts
  google_fonts: ^6.1.0

  #images
  transparent_image: ^2.0.1

  #state management 
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9

  #language
  easy_localization: ^3.0.4

  #select country
  country_picker: ^2.0.17

  #slider
  carousel_slider: ^4.1.1

  #webview
  webview_flutter: ^4.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/language/
  #   - images/a_dot_ham.jpeg

