import 'package:flutter/material.dart';

import '../styles/color_styles.dart';

final ThemeData themeLight = ThemeData(
  useMaterial3: false,
  fontFamily: 'SairaSemiCondensed',
  primarySwatch: const MaterialColor(4282476755, {
    50: Color(0xffeaeffa),
    100: Color(0xffd6def5),
    200: Color(0xffacbdec),
    300: Color(0xff839ce2),
    400: Color(0xff597bd9),
    500: Color(0xff305acf),
    600: Color(0xff2648a6),
    700: Color(0xff1d367c),
    800: Color(0xff132453),
    900: Color(0xff0a1229)
  }),
  brightness: Brightness.light,
  primaryColorLight: const Color(0xffd6def5),
  primaryColorDark: const Color(0xff1d367c),
  canvasColor: const Color(0xFFf2f2f6),
  scaffoldBackgroundColor: const Color(0xFFf2f2f6),
  bottomAppBarTheme: const BottomAppBarTheme(color: Color(0xffffffff)),
  cardColor: const Color(0xffffffff),
  dividerColor: const Color(0x1f000000),
  splashColor: const Color(0x66c8c8c8),
  unselectedWidgetColor: const Color(0x8a000000),
  disabledColor: const Color(0x61000000),
  secondaryHeaderColor: const Color(0xffeaeffa),
  dialogBackgroundColor: const Color(0xffffffff),
  indicatorColor: const Color(0xff305acf),
  hintColor: const Color(0x8a000000),
  buttonTheme: const ButtonThemeData(
    textTheme: ButtonTextTheme.normal,
    minWidth: 88,
    height: 36,
    padding: EdgeInsets.only(top: 0, bottom: 0, left: 16, right: 16),
    shape: RoundedRectangleBorder(
      side: BorderSide(
        color: Color(0xff000000),
        width: 0,
        style: BorderStyle.none,
      ),
      borderRadius: BorderRadius.all(Radius.circular(2.0)),
    ),
    alignedDropdown: false,
    buttonColor: Color(0xffe0e0e0),
    disabledColor: Color(0x61000000),
    highlightColor: Color(0x29000000),
    splashColor: Color(0x1f000000),
    focusColor: Color(0x1f000000),
    hoverColor: Color(0x0a000000),
    colorScheme: ColorScheme(
      primary: Color(0xff4168d3),
      secondary: Color(0xff305acf),
      surface: Color(0xffffffff),
      background: Color(0xffacbdec),
      error: Color(0xffd32f2f),
      onPrimary: Color(0xffffffff),
      onSecondary: Color(0xffffffff),
      onSurface: Color(0xff000000),
      onBackground: Color(0xffffffff),
      onError: Color(0xffffffff),
      brightness: Brightness.light,
    ),
  ),
  textTheme: const TextTheme(
    displayLarge: TextStyle(fontSize: 60),
    displayMedium: TextStyle(fontSize: 50),
    displaySmall: TextStyle(fontSize: 40),
    headlineMedium: TextStyle(fontSize: 30),
    headlineSmall: TextStyle(fontSize: 20),
    titleLarge: TextStyle(fontSize: 16),
  ),
  appBarTheme: const AppBarTheme(
    color: Colors.white,
    centerTitle: true,
    elevation: 1,
    titleTextStyle: TextStyle(
        color: ColorStyles.purpleBlue,
        fontSize: 16,
        fontWeight: FontWeight.bold),
    iconTheme: IconThemeData(
      color: Color(0xff323c4a),
    ),
  ),
);
